services:
  nginxproxymanager: 
    image: jlesage/nginx-proxy-manager
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      # web ui : Port used to access the web interface of the application.NOTE: This applies only when Network Type is set to Bridge. For other network types, port 8181 should be used instead.
      - 7818:8181
      # Port used to serve HTTP requests.NOTE: Your router should be configured to forward port 80 to this port. If your router doesn't allow setting the destination/internal IP address, this must be set to 80.NOTE: This applies only when Network Type is set to Bridge. For other network types, port 8080 should be used instead.
      - 18080:18080
      # Port used to serve HTTPs requests.NOTE: Your router should be configured to forward port 443 to this port. If your router doesn't allow setting the destination/internal IP address, this must be set to 443.NOTE: This applies only when Network Type is set to Bridge. For other network types, port 4443 should be used instead.
      - 18443:4443
    environment:
      #   When set to '1', IPv6 support is disabled.
      - DISABLE_IPV6=0
      # for permission issue
      - PUID=0
      - PGID=0
      - TZ=Asia/Taipei
    volumes:
      - /mnt/appdata/NginxProxyManager:/config
    networks:
      - appnetwork
networks:
  appnetwork:
    name: mynetwork
    external: true
      
      