version: "3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
    # don't put in this git repo 
      - ${PWD}/portainer-ce/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
# network lifecycle controlled by portainer
networks:
  app_network:
    name: mynetwork
      


