version: "3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    ports:
    # https
      - 9443:9443
    # http
      - 9000:9000
    environment:
      - TZ=Asia/Taipei
    volumes:
    # don't put in this git repo
      # - ${PWD}/portainer-ce/data:/data
      - /mnt/appdata/portainer-ce/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    



  # problem maker, I rather update manually
  # watchtower:
  #   image: containrrr/watchtower
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --interval 86400



