# TODO
services:
  aria2_pro: 
    image: p3terx/aria2-pro
    container_name: aria2_pro
    ports:
    # bind RPC listen port.
      - 46800:6800
    # Bind BT listen port (TCP).
      - 46888:6888
    # Bind BT listen port (TCP).
      - 46888:6888/udp
  
    volumes:
    # Location of downloads on disk.
      - /mnt/disks/2t/aria2DownloadPool:/downloads
    # Contains all relevant configuration files.
      - /mnt/user/appdata/aria2-pro:/config
    env_file: .env
