# TODO
services:
  aria2_pro: 
    image: p3terx/aria2-pro
    container_name: aria2_pro
    ports:
    # dns udp
      - 53:53
    # dns over tls
      - 853:853
    # 853:853 udp
      - 853:853/udp
    # WebUI:
    volumes:
    environment:
      - RPC_SECRET=6319
