name: vaultwarden
services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    container_name: vaultwarden
    environment:
      - TZ=Asia/Taipei
    volumes:
        - /mnt/appdata/vaultwarden:/data/
    ports:
        - 40080:80

