# author: df
# version: 1.0
# date: 2024.8.8
# description: wyoming_faster_whisper
# doc: https://github.com/hass-demacia/wyoming_faster_whisper
# this is gpu wrap version

version: '3.8'
services:
  whisper:
    image: ghcr.io/hass-demacia/wyoming_faster_whisper:dev
    restart: unless-stopped
    container_name: whisper
    ports:
      - "10300:10300"
    volumes:
      - /mnt/appdata/wyoming:/data
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
    command:
      - "--language zh"
      - "--log-format '%(asctime)s [%(levelname)s]%(message)s' "
      - "--device cuda"
      - "--model medium"
      - "--initial-prompt 以下是基於台灣繁體中文的語音句子"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
