#!/usr/bin/env python3
"""Verify Android native config generated by Expo prebuild."""

from __future__ import annotations

import json
import pathlib
import xml.etree.ElementTree as ET


ROOT = pathlib.Path(__file__).resolve().parents[1]
APP_JSON = ROOT / "app.json"
MANIFEST = ROOT / "android" / "app" / "src" / "main" / "AndroidManifest.xml"
GRADLE_WRAPPER = ROOT / "android" / "gradle" / "wrapper" / "gradle-wrapper.properties"
ANDROID_NS = "{http://schemas.android.com/apk/res/android}"
LOCAL_HTTP_PLUGIN = "./plugins/with-local-http-android"
EXPECTED_GRADLE_DISTRIBUTION = (
    "https\\://services.gradle.org/distributions/gradle-8.14.3-bin.zip"
)


def read_gradle_distribution() -> str | None:
    if not GRADLE_WRAPPER.exists():
        return None

    for line in GRADLE_WRAPPER.read_text(encoding="utf-8").splitlines():
        key, separator, value = line.partition("=")
        if separator and key == "distributionUrl":
            return value.strip()
    return None


def main() -> int:
    app = json.loads(APP_JSON.read_text(encoding="utf-8"))
    plugins = app["expo"].get("plugins", [])
    if LOCAL_HTTP_PLUGIN not in plugins:
        print(f"missing app.json plugin: {LOCAL_HTTP_PLUGIN}")
        return 1

    if not MANIFEST.exists():
        print("AndroidManifest.xml missing; run npm run prebuild:android first")
        return 1

    root = ET.parse(MANIFEST).getroot()
    application = root.find("application")
    if application is None:
        print("AndroidManifest.xml has no <application>")
        return 1

    cleartext = application.attrib.get(f"{ANDROID_NS}usesCleartextTraffic")
    if cleartext != "true":
        print("android:usesCleartextTraffic must be true for local HTTP providers")
        return 1

    distribution_url = read_gradle_distribution()
    if distribution_url is None:
        print("Gradle wrapper distributionUrl missing; run npm run prebuild:android first")
        return 1

    if distribution_url != EXPECTED_GRADLE_DISTRIBUTION:
        print(
            "Gradle wrapper must use "
            f"{EXPECTED_GRADLE_DISTRIBUTION}; got {distribution_url}"
        )
        return 1

    print("android config verification passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
