services:
  hentaiathome: 
    image: d0v0b/hentaiathome
    container_name: hentaiathome
    restart: unless-stopped
    ports:
      - 5487:5487
    volumes:
      # appdata 
      - /mnt/sdaDATA/H@H:/hath
    environment:
      - CLIENT_ID=28238
      - CLIENT_KEY=xnHXaKHndnrtXX2Ee7MU
    networks:
      - appnetwork

networks:
  appnetwork:
    name: mynetwork
    external: true
      
  