version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    environment:
    # for dealing with the annoying permission issue
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
    volumes:
      - /mnt/appdata/nextcloud:/config
      - /mnt/mydata/Nextcloud-data:/data
    ports:
      - 5443:443
    networks:
      - appnetwork
networks:
  appnetwork:
    name: mynetwork
    external: true
          