version: "3.8"
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: unless-stopped
    ports:
      - "48888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: df@dfder.tw
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:

  pgadmin-data: