# author : df
# version: 1.0
# date: 2024.10.24
# description: open-webui
# doc: https://github.com/open-webui/open-webui

version: '3.8'

services:
  chatStack:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui-ollamaStack
    ports:
      - "43000:8080"
    volumes:
      - /mnt/appdata/ollamaStack/ollama:/root/.ollama
      - /mnt/appdata/ollamaStack/open-webui:/app/backend/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  chatgpt-next-web:
    image: yidadaa/chatgpt-next-web
    environment:
      - OPENAI_API_KEY=
      - CODE=6319
    ports:
      - "33000:3000"
    restart: unless-stopped

  duck2api:
    image: ghcr.io/aurora-develop/duck2api:latest
    container_name: duck2api
    restart: unless-stopped
    ports:
      - '28080:28080'
    environment:
      - Authorization=123
