#!/bin/sh
set -eu

# Validate one real, merged Portainer stack environment before it is loaded in
# the UI. The file is parsed by Docker Compose and is never sourced here. The
# caller supplies the exact UI Stack Name because Portainer overrides
# COMPOSE_PROJECT_NAME with that value.

repo_root=$(CDPATH='' cd -- "$(dirname "$0")/.." && pwd)
compose_file=$repo_root/docker-compose.yml
helper=$repo_root/scripts/ddns-openvpn.sh
asset_source=/home/df/.local/share/ddns-vpn-proxy/assets/2026-07-18.5
private_root=/home/df/.local/share/ddns-vpn-proxy/private/2026-07-18.5
runtime_root=/home/df/.local/share/ddns-vpn-proxy/runtime/2026-07-18.5
tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT HUP INT TERM

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

[ "$#" -eq 3 ] ||
  die "usage: $0 REGION STACK_NAME ENV_FILE (REGION is jp, romania or uk)"
region=$1
stack_name=$2
env_file=$3

for command_name in awk cmp dirname docker env find grep jq mktemp rm sed sha256sum stat wc
do
  command -v "$command_name" >/dev/null 2>&1 ||
    die "required command not found: $command_name"
done
docker compose version >/dev/null 2>&1 || die 'docker compose is required'

[ -f "$env_file" ] && [ ! -L "$env_file" ] ||
  die 'env file is missing, not regular, or is a symlink'
[ "$(stat -c '%a' "$env_file")" = 600 ] ||
  die 'real env files must be mode 0600'

# Portainer stores every submitted environment entry, including variables that
# Compose does not consume. Keep the submitted file to the reviewed, non-secret
# interpolation contract and reject duplicate/"export" syntax before Compose
# parses it.
LC_ALL=C awk '
  BEGIN {
    split("COMPOSE_PROJECT_NAME PRIVATE_REGION TZ VPN_TYPE VPN_CONFIG_FILE VPN_SOURCE_SHA256 " \
      "GLUETUN_CONTAINER_NAME VPROXY_CONTAINER_NAME HTTP_PROXY_PORT " \
      "SOCKS5_PROXY_PORT SHADOWSOCKS_TCP_PORT SHADOWSOCKS_UDP_PORT " \
      "DDNS_HOSTNAME DDNS_POLL_SECONDS DDNS_INIT_RETRY_SECONDS " \
      "DDNS_INIT_TIMEOUT_SECONDS DDNS_RESOLVER DDNS_OVERRIDE_IPS " \
      "PROXY_BIND_ADDRESS HTTPPROXY HTTPPROXY_STEALTH " \
      "SHADOWSOCKS SHADOWSOCKS_LOG SHADOWSOCKS_CIPHER " \
      "GLUETUN_HEALTH_TIMEOUT_SECONDS OPENVPN_VERBOSITY LOG_MAX_SIZE LOG_MAX_FILE", \
      names, " ")
    for (i in names) allowed[names[i]] = 1
  }
  /^[[:space:]]*(#|$)/ { next }
  !/^[A-Za-z_][A-Za-z0-9_]*=/ { exit 2 }
  {
    key = $0
    sub(/=.*/, "", key)
    if (!(key in allowed) || seen[key]++) exit 3
  }
' "$env_file" || die 'Portainer env contains an unknown, duplicate, or invalid entry'

# The API key is generated by the asset installer and mounted from a private
# host directory. It must never be copied into Portainer's environment store.
if grep -Eq '^[[:space:]]*(GLUETUN_CONTROL_API_KEY|GLUETUN_CONTROL_API_KEY_FILE|HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH|OPENVPN_USER|OPENVPN_PASSWORD|HTTPPROXY_USER|HTTPPROXY_PASSWORD|SOCKS5_USER|SOCKS5_PASSWORD|SHADOWSOCKS_PASSWORD)[[:space:]]*=' \
  "$env_file"; then
  die 'control API key, auth path, or proxy credential must not be present in the Portainer env file'
fi

case $region in
  jp)
    expected_project=ddns-vpn-proxy-jp
    expected_gluetun=gluetun-jp
    expected_vproxy=gluetun-jp-vproxy
    expected_profile=jp-tok.prod.surfshark.com_udp.ovpn
    expected_profile_hash=32805d1325c6ac9364c9370a48c314dc5701547ac1de1246f6a8f9a0c0bae648
    expected_http=19010
    expected_socks=19110
    expected_ss_tcp=19011
    expected_ss_udp=19011
    expected_private_region=jp
    ;;
  romania)
    expected_project=ddns-vpn-proxy-romania
    expected_gluetun=gluetun-romania
    expected_vproxy=gluetun-romania-vproxy
    expected_profile=ro-buc.prod.surfshark.com_udp.ovpn
    expected_profile_hash=4766944557b366f52abc623aa46aa2577ea03a4f6e6f013ed28f8164ea8174e1
    expected_http=19015
    expected_socks=19115
    expected_ss_tcp=19016
    expected_ss_udp=19017
    expected_private_region=romania
    ;;
  uk)
    expected_project=ddns-vpn-proxy-uk
    expected_gluetun=gluetun-uk
    expected_vproxy=gluetun-uk-vproxy
    expected_profile=uk-lon.prod.surfshark.com_udp.ovpn
    expected_profile_hash=52e38544276aeaf4d0bbcba8821778ee8105a02ef681bf678850121fbccc03d2
    expected_http=19020
    expected_socks=19120
    expected_ss_tcp=19021
    expected_ss_udp=19021
    expected_private_region=uk
    ;;
  *) die "unknown region: $region" ;;
esac

[ "$stack_name" = "$expected_project" ] ||
  die "Portainer Stack Name must be exactly: $expected_project"
private_source=$private_root/$expected_private_region
installed_profile=$asset_source/profiles/$expected_profile
if [ "$(grep -Ec '^PRIVATE_REGION=' "$env_file")" -ne 1 ] ||
   ! grep -Fxq "PRIVATE_REGION=$expected_private_region" "$env_file"; then
  die "PRIVATE_REGION must be exactly: $expected_private_region"
fi
if [ "$(grep -Ec '^VPN_SOURCE_SHA256=' "$env_file")" -ne 1 ] ||
   ! grep -Fxq "VPN_SOURCE_SHA256=$expected_profile_hash" "$env_file"; then
  die 'VPN_SOURCE_SHA256 must exactly match the reviewed selected profile digest'
fi

verify_installed_assets() {
  [ -d "$asset_source" ] && [ ! -L "$asset_source" ] ||
    die "reviewed assets are missing: $asset_source"
  [ "$(stat -c '%a' "$asset_source")" = 500 ] ||
    die 'reviewed asset directory must be mode 0500'
  [ -d "$asset_source/profiles" ] && [ ! -L "$asset_source/profiles" ] ||
    die 'reviewed profile directory is missing or symlinked'
  [ "$(stat -c '%a' "$asset_source/profiles")" = 500 ] ||
    die 'reviewed profile directory must be mode 0500'
  for asset_file in ddns-openvpn.sh "profiles/$expected_profile"
  do
    [ -f "$asset_source/$asset_file" ] && [ ! -L "$asset_source/$asset_file" ] ||
      die "reviewed asset is missing or symlinked: $asset_file"
    [ "$(stat -c '%a' "$asset_source/$asset_file")" = 400 ] ||
      die "reviewed asset must be mode 0400: $asset_file"
  done
  cmp -s "$helper" "$asset_source/ddns-openvpn.sh" ||
    die 'installed helper does not match the reviewed repository helper'
  profile_hash_line=$(sha256sum "$installed_profile") ||
    die 'failed to hash the selected installed VPN profile'
  profile_hash=${profile_hash_line%% *}
  [ "$profile_hash" = "$expected_profile_hash" ] ||
    die 'selected installed VPN profile does not match its reviewed digest'
}

verify_private_credential() {
  credential_file=$1
  [ -f "$credential_file" ] && [ ! -L "$credential_file" ] ||
    die 'private credential is missing or symlinked'
  [ "$(stat -c '%a' "$credential_file")" = 400 ] ||
    die 'private credential must be mode 0400'
  LC_ALL=C awk '
    BEGIN { lines = 0 }
    {
      if ($0 == "" || $0 ~ /[[:cntrl:]]/) exit 1
      lines++
    }
    END { exit(lines == 1 ? 0 : 1) }
  ' "$credential_file" ||
    die 'private credential must be one non-empty printable line'
}

verify_status_only_private_tree() {
  [ -d "$private_source" ] && [ ! -L "$private_source" ] ||
    die "private control assets are missing: $private_source"
  [ "$(stat -c '%a' "$private_source")" = 500 ] ||
    die 'private control asset directory must be mode 0500'
  for private_file in \
    control-api-key \
    control-auth.toml \
    control-default-role.json \
    openvpn-user \
    openvpn-password \
    httpproxy-user \
    httpproxy-password \
    shadowsocks-password
  do
    [ -f "$private_source/$private_file" ] && [ ! -L "$private_source/$private_file" ] ||
      die "private control asset is missing or symlinked: $private_file"
    [ "$(stat -c '%a' "$private_source/$private_file")" = 400 ] ||
      die "private control asset must be mode 0400: $private_file"
  done
  [ "$(find "$private_source" -mindepth 1 -maxdepth 1 | wc -l)" -eq 8 ] ||
    die 'private control asset directory contains an unexpected entry'

  key=$(sed -n '1p' "$private_source/control-api-key")
  [ "$(wc -l <"$private_source/control-api-key")" -eq 1 ] ||
    die 'control API key must contain exactly one line'
  [ "$(wc -c <"$private_source/control-api-key")" -eq 65 ] ||
    die 'control API key has an invalid length'
  case $key in
    ''|*[!0-9a-f]*) die 'control API key must be lowercase hexadecimal' ;;
  esac
  [ "${#key}" -eq 64 ] || die 'control API key must contain 64 characters'

  default_role=$(sed -n '1p' "$private_source/control-default-role.json")
  default_key=$(printf '%s\n' "$default_role" |
    sed -n 's/^{"name":"deny-default","auth":"apikey","apikey":"\([0-9a-f]*\)"}$/\1/p')
  case $default_key in
    ''|*[!0-9a-f]*) die 'default control role key must be lowercase hexadecimal' ;;
  esac
  [ "${#default_key}" -eq 64 ] || die 'default control role key must contain 64 characters'
  [ "$(wc -l <"$private_source/control-default-role.json")" -eq 1 ] ||
    die 'default control role must contain exactly one line'
  [ "$default_role" = "{\"name\":\"deny-default\",\"auth\":\"apikey\",\"apikey\":\"$default_key\"}" ] ||
    die 'default control role is not the reviewed deny role'
  [ "$default_key" != "$key" ] ||
    die 'default control role key must differ from watcher key'

  expected_auth=$( {
    printf '%s\n' '[[roles]]'
    printf '%s\n' 'name = "ddns-watcher"'
    printf '%s\n' 'auth = "apikey"'
    printf 'apikey = "%s"\n' "$key"
    printf '%s\n' 'routes = ["PUT /v1/vpn/status"]'
  } )
  actual_auth=$(sed -n '1,5p' "$private_source/control-auth.toml")
  [ "$(wc -l <"$private_source/control-auth.toml")" -eq 5 ] ||
    die 'control auth role must contain exactly five lines'
  [ "$actual_auth" = "$expected_auth" ] ||
    die 'control auth role is not the reviewed status-only role'
  case $actual_auth in
    *'/v1/vpn/settings'*) die 'control auth role must not grant settings access' ;;
  esac

  for credential_name in \
    openvpn-user \
    openvpn-password \
    httpproxy-user \
    httpproxy-password \
    shadowsocks-password
  do
    verify_private_credential "$private_source/$credential_name"
  done
}

verify_runtime_resolver() {
  runtime_file=$runtime_root/$expected_private_region/resolv.conf
  [ -d "$runtime_root" ] && [ ! -L "$runtime_root" ] ||
    die "runtime resolver root is missing or symlinked: $runtime_root"
  [ "$(stat -c '%a' "$runtime_root")" = 500 ] ||
    die 'runtime resolver root must be mode 0500'
  [ "$(find "$runtime_root" -mindepth 1 -maxdepth 1 | wc -l)" -eq 3 ] ||
    die 'runtime resolver root contains an unexpected region'
  for runtime_region in jp romania uk
  do
    [ -d "$runtime_root/$runtime_region" ] && [ ! -L "$runtime_root/$runtime_region" ] ||
      die "runtime resolver region is missing or symlinked: $runtime_region"
    [ "$(stat -c '%a' "$runtime_root/$runtime_region")" = 500 ] ||
      die "runtime resolver region must be mode 0500: $runtime_region"
    [ "$(find "$runtime_root/$runtime_region" -mindepth 1 -maxdepth 1 | wc -l)" -eq 1 ] ||
      die "runtime resolver region contains an unexpected entry: $runtime_region"
  done
  [ -f "$runtime_file" ] && [ ! -L "$runtime_file" ] ||
    die 'selected runtime resolver file is missing or symlinked'
  [ "$(stat -c '%a' "$runtime_file")" = 600 ] ||
    die 'selected runtime resolver file must be mode 0600'
  [ "$(stat -c '%u:%g' "$runtime_file")" = 1000:1000 ] ||
    die 'selected runtime resolver file must be owned by UID/GID 1000'
  [ "$(stat -c '%h' "$runtime_file")" = 1 ] ||
    die 'selected runtime resolver file must not be hard-linked'
  [ "$(wc -l <"$runtime_file")" -eq 1 ] ||
    die 'selected runtime resolver file must contain one line'
  [ "$(sed -n '1p' "$runtime_file")" = 'nameserver 127.0.0.1' ] ||
    die 'selected runtime resolver file must start fail-closed at loopback'
}

verify_installed_assets
verify_status_only_private_tree
verify_runtime_resolver

# The first model validates COMPOSE_PROJECT_NAME in the env file. The second
# supplies -p to reproduce Portainer's authoritative UI Stack Name behavior.
env_model=$tmpdir/env-model.json
model=$tmpdir/portainer-model.json
env -i PATH="$PATH" HOME="${HOME:-/root}" \
  docker compose --file "$compose_file" --env-file "$env_file" \
  config --format json >"$env_model"
env -i PATH="$PATH" HOME="${HOME:-/root}" \
  docker compose --project-name "$stack_name" --file "$compose_file" \
  --env-file "$env_file" config --format json >"$model"

[ "$(jq -r '.services.gluetun.command | length' "$model")" -eq 1 ] ||
  die 'Gluetun point-of-use wrapper must be exactly one command'
command_hash_line=$(jq -j '.services.gluetun.command[0]' "$model" | sha256sum) ||
  die 'failed to hash Gluetun point-of-use wrapper'
command_hash=${command_hash_line%% *}
[ "$command_hash" = 818bac587fb2684e60a4837d1d42b637d74531130608263a44c2daa72f101f14 ] ||
  die 'Gluetun point-of-use wrapper differs from the reviewed exact command'

jq -e --arg project "$expected_project" '.name == $project' \
  "$env_model" >/dev/null ||
  die "COMPOSE_PROJECT_NAME in the env file must be exactly: $expected_project"

# Keep all rendered-model assertions in jq so no credential value is printed.
jq -e \
  --arg project "$expected_project" \
  --arg gluetun "$expected_gluetun" \
  --arg vproxy "$expected_vproxy" \
  --arg helper_image "alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b" \
  --arg gluetun_image "ddns-vpn-gluetun:v3.41.1-patched-20260718" \
  --arg vproxy_image "ddns-vpn-gost:3.3.0-5a01aa4-alpine3.24.1" \
  --arg build_context "$repo_root" \
  --arg helper_source "$asset_source/ddns-openvpn.sh" \
  --arg profile "/opt/ddns-profile/client.ovpn" \
  --arg profile_source "$installed_profile" \
  --arg profile_hash "$expected_profile_hash" \
  --arg http "$expected_http" \
  --arg socks "$expected_socks" \
  --arg ss_tcp "$expected_ss_tcp" \
  --arg ss_udp "$expected_ss_udp" \
  --arg asset_source "$asset_source" \
  --arg private_source "$private_source" \
  --arg runtime_source "$runtime_root/$expected_private_region/resolv.conf" \
  '
    def has_port($target; $published; $protocol):
      any(.services.gluetun.ports[];
        .target == $target and
        (.published | tostring) == $published and
        .protocol == $protocol and
        .host_ip == "127.0.0.1");
    def readonly_bind($service; $source; $target):
      any(.services[$service].volumes[];
        .type == "bind" and
        .source == $source and
        .target == $target and
        .read_only == true and
        .bind.create_host_path == false);
    def named_volume($service; $source; $target; $read_only):
      any(.services[$service].volumes[];
        .type == "volume" and
        .source == $source and
        .target == $target and
        (.read_only // false) == $read_only);
    def exact_keys($expected): ((keys | sort) == ($expected | sort));
    def reviewed_logging:
      {"driver":"json-file","options":{"max-file":"3","max-size":"10m"}};
    def reviewed_helper_environment:
      {
        "DDNS_HOSTNAME":"",
        "DDNS_INIT_RETRY_SECONDS":"5",
        "DDNS_INIT_TIMEOUT_SECONDS":"120",
        "DDNS_OVERRIDE_IPS":"",
        "DDNS_POLL_SECONDS":"60",
        "DDNS_RESOLVER":"",
        "GLUETUN_CONTROL_API_KEY_FILE":"/run/ddns-private/control-api-key",
        "GLUETUN_CONTROL_AUTH_CONFIG_FILEPATH":"/run/ddns-private/control-auth.toml",
        "GLUETUN_CONTROL_DEFAULT_ROLE_FILE":"/run/ddns-private/control-default-role.json",
        "GLUETUN_HEALTHCHECK_URL":"http://gluetun:9999",
        "GLUETUN_HEALTH_TIMEOUT_SECONDS":"120",
        "HTTPPROXY_ENABLED":"on",
        "HTTPPROXY_PASSWORD_CONFIGURED":"1",
        "HTTPPROXY_PASSWORD_SECRETFILE":"/run/ddns-private/httpproxy-password",
        "HTTPPROXY_USER_CONFIGURED":"1",
        "HTTPPROXY_USER_SECRETFILE":"/run/ddns-private/httpproxy-user",
        "OPENVPN_PASSWORD_CONFIGURED":"1",
        "OPENVPN_PASSWORD_SECRETFILE":"/run/ddns-private/openvpn-password",
        "OPENVPN_USER_CONFIGURED":"1",
        "OPENVPN_USER_SECRETFILE":"/run/ddns-private/openvpn-user",
        "PROXY_BIND_ADDRESS":"127.0.0.1",
        "SHADOWSOCKS_ENABLED":"on",
        "SHADOWSOCKS_PASSWORD_CONFIGURED":"1",
        "SHADOWSOCKS_PASSWORD_SECRETFILE":"/run/ddns-private/shadowsocks-password",
        "SOCKS5_PASSWORD_CONFIGURED":"0",
        "SOCKS5_USER_CONFIGURED":"0",
        "STATE_DIR":"/state",
        "TZ":"Asia/Taipei",
        "VPN_RENDERED_CONFIG":"/state/runtime/vpn.conf",
        "VPN_SOURCE_CONFIG":"/opt/ddns-profile/client.ovpn",
        "VPN_SOURCE_SHA256":$profile_hash,
        "VPN_TYPE":"openvpn"
      };
    def reviewed_gluetun_environment:
      {
        "FIREWALL_INPUT_PORTS":"8888,1080,8388,8000,9999",
        "HEALTH_RESTART_VPN":"on",
        "HEALTH_SERVER_ADDRESS":":9999",
        "HEALTH_SMALL_CHECK_TYPE":"dns",
        "HTTPPROXY":"on",
        "HTTPPROXY_LISTENING_ADDRESS":":8888",
        "HTTPPROXY_PASSWORD_SECRETFILE":"/run/ddns-private/httpproxy-password",
        "HTTPPROXY_STEALTH":"off",
        "HTTPPROXY_USER_SECRETFILE":"/run/ddns-private/httpproxy-user",
        "HTTP_CONTROL_SERVER_ADDRESS":":8000",
        "HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH":"/run/ddns-private/control-auth.toml",
        "OPENVPN_CUSTOM_CONFIG":"/state/runtime/vpn.conf",
        "OPENVPN_FLAGS":"--group nonrootuser --cipher AES-256-GCM --data-ciphers AES-256-GCM",
        "OPENVPN_PASSWORD_SECRETFILE":"/run/ddns-private/openvpn-password",
        "OPENVPN_USER_SECRETFILE":"/run/ddns-private/openvpn-user",
        "OPENVPN_VERBOSITY":"1",
        "SHADOWSOCKS":"on",
        "SHADOWSOCKS_CIPHER":"chacha20-ietf-poly1305",
        "SHADOWSOCKS_LISTENING_ADDRESS":":8388",
        "SHADOWSOCKS_LOG":"off",
        "SHADOWSOCKS_PASSWORD_SECRETFILE":"/run/ddns-private/shadowsocks-password",
        "TZ":"Asia/Taipei",
        "VPN_SERVICE_PROVIDER":"custom",
        "VPN_TYPE":"openvpn"
      };
    def ro_bind($source; $target):
      {"type":"bind","source":$source,"target":$target,"read_only":true,
       "bind":{"create_host_path":false}};
    def rw_bind($source; $target):
      {"type":"bind","source":$source,"target":$target,
       "bind":{"create_host_path":false}};
    def rw_state:
      {"type":"volume","source":"vpn-state","target":"/state","volume":{}};
    def ro_state:
      {"type":"volume","source":"vpn-state","target":"/state","read_only":true,"volume":{}};

    exact_keys(["name","networks","services","volumes","x-ddns-common","x-logging"]) and
    (.networks == {"default":{"name":($project + "_default"),"ipam":{}}}) and
    (.volumes == {"vpn-state":{"name":($project + "_vpn-state")}}) and
    (."x-logging" == reviewed_logging) and
    (."x-ddns-common" | exact_keys([
      "cap_add","cap_drop","entrypoint","environment","image","logging","pull_policy",
      "read_only","security_opt","tmpfs","volumes"])) and
    (."x-ddns-common".environment == reviewed_helper_environment) and
    (."x-ddns-common".logging == reviewed_logging) and
    (.services."ddns-init" | exact_keys([
      "cap_add","cap_drop","command","entrypoint","environment","image","logging","networks",
      "pull_policy","read_only","restart","security_opt","tmpfs","volumes"])) and
    (.services."ddns-watcher" | exact_keys([
      "cap_add","cap_drop","command","depends_on","entrypoint","environment","healthcheck",
      "image","logging","networks","pull_policy","read_only","restart","security_opt","tmpfs","volumes"])) and
    (.services.gluetun | exact_keys([
      "build","cap_add","cap_drop","command","container_name","depends_on","devices","entrypoint",
      "environment","healthcheck","image","logging","networks","ports","pull_policy","read_only",
      "restart","security_opt","stop_grace_period","tmpfs","volumes"])) and
    (.services.vproxy | exact_keys([
      "build","cap_drop","command","container_name","depends_on","entrypoint","healthcheck","image",
      "logging","mem_limit","network_mode","pids_limit","pull_policy","read_only","restart",
      "security_opt","stop_grace_period","tmpfs","ulimits","user"])) and
    (.services."ddns-init".networks == {"default":null}) and
    (.services."ddns-watcher".networks == {"default":null}) and
    (.services.gluetun.networks == {"default":null}) and
    (all(.services[]; .logging == reviewed_logging)) and
    (.services."ddns-init".environment == reviewed_helper_environment) and
    (.services."ddns-watcher".environment == reviewed_helper_environment) and
    (.services.gluetun.environment == reviewed_gluetun_environment) and
    (.name == $project) and
    (([.services | keys[]] | sort) ==
      (["ddns-init", "ddns-watcher", "gluetun", "vproxy"] | sort)) and
    (.services.gluetun.container_name == $gluetun) and
    (.services.vproxy.container_name == $vproxy) and
    (.services.vproxy.network_mode == "service:gluetun") and
    (.services."ddns-init".image == $helper_image) and
    (.services."ddns-watcher".image == $helper_image) and
    (.services.gluetun.image == $gluetun_image) and
    (.services.vproxy.image == $vproxy_image) and
    (.services."ddns-init".pull_policy == "always") and
    (.services."ddns-watcher".pull_policy == "always") and
    (.services.gluetun.pull_policy == "build") and
    (.services.vproxy.pull_policy == "build") and
    (.services.gluetun.build ==
      {"context":$build_context,"dockerfile":"docker/gluetun.Dockerfile"}) and
    (.services.vproxy.build ==
      {"context":$build_context,"dockerfile":"docker/gost.Dockerfile"}) and

    (.services."ddns-init".command == ["init"]) and
    (.services."ddns-watcher".command == ["watch"]) and
    (.services."ddns-init".entrypoint == ["/bin/sh", "/usr/local/bin/ddns-openvpn.sh"]) and
    (.services."ddns-watcher".entrypoint == ["/bin/sh", "/usr/local/bin/ddns-openvpn.sh"]) and
    (.services.vproxy.entrypoint == ["/usr/local/bin/gost"]) and
    (.services.vproxy.command == ["-L",
      "socks5://0.0.0.0:1080?handler.bind=false&handler.notls=true&handler.readTimeout=5s&handler.udp=false&service.dialTimeout=10s"]) and
    (.services."ddns-init".restart == "no") and
    (.services."ddns-watcher".restart == "unless-stopped") and
    (.services.gluetun.restart == "unless-stopped") and
    (.services.vproxy.restart == "unless-stopped") and
    ((.services."ddns-init".depends_on // {}) == {}) and
    (.services.gluetun.depends_on ==
      {"ddns-init":{"condition":"service_completed_successfully","required":true}}) and
    (.services.vproxy.depends_on ==
      {"gluetun":{"condition":"service_healthy","required":true}}) and
    (.services."ddns-watcher".depends_on ==
      {"gluetun":{"condition":"service_healthy","required":true},
       "vproxy":{"condition":"service_healthy","required":true}}) and

    (all(.services[];
      (.privileged // false) == false and
      ((.pid // "") == "") and
      ((.ipc // "") == "") and
      .read_only == true and
      .security_opt == ["no-new-privileges:true"] and
      .cap_drop == ["ALL"])) and
    (.services."ddns-init".cap_add == ["DAC_READ_SEARCH"]) and
    (.services."ddns-watcher".cap_add == ["DAC_READ_SEARCH"]) and
    (.services.gluetun.cap_add ==
      ["NET_ADMIN", "CHOWN", "DAC_OVERRIDE", "KILL", "SETGID", "SETUID"]) and
    (((.services.vproxy.cap_add // []) | length) == 0) and
    (.services.vproxy.user == "65532:65532") and
    (.services.vproxy.mem_limit == "134217728") and
    (.services.vproxy.pids_limit == 64) and
    (.services.vproxy.ulimits == {"nofile":{"soft":1024,"hard":1024}}) and
    (.services.vproxy.stop_grace_period == "10s") and
    (.services."ddns-init".tmpfs == ["/tmp:size=8m,mode=1777"]) and
    (.services."ddns-watcher".tmpfs == ["/tmp:size=8m,mode=1777"]) and
    ((.services.gluetun.tmpfs | sort) ==
      (["/tmp:size=16m,mode=1777", "/etc/openvpn:size=4m,mode=0755",
        "/gluetun:size=8m,mode=0755"] | sort)) and
    (.services.vproxy.tmpfs == ["/tmp:size=8m,mode=1777"]) and
    (.services.gluetun.devices ==
      [{"source":"/dev/net/tun","target":"/dev/net/tun","permissions":"rwm"}]) and

    (.services.gluetun.healthcheck ==
      {"test":["CMD","/gluetun-entrypoint","healthcheck"],
       "timeout":"5s","interval":"5s","retries":3,"start_period":"10s"}) and
    (.services.vproxy.healthcheck ==
      {"test":["CMD","/usr/local/bin/gost-healthcheck"],
       "timeout":"3s","interval":"10s","retries":3,"start_period":"5s"}) and
    (.services."ddns-watcher".healthcheck ==
      {"test":["CMD","/bin/sh","/usr/local/bin/ddns-openvpn.sh","healthcheck"],
       "timeout":"5s","interval":"30s","retries":3,"start_period":"30s"}) and

    (.services."ddns-init".environment.VPN_TYPE == "openvpn") and
    (.services."ddns-watcher".environment.VPN_TYPE == "openvpn") and
    (.services.gluetun.environment.VPN_TYPE == "openvpn") and
    (.services.gluetun.environment.VPN_SERVICE_PROVIDER == "custom") and
    (.services."ddns-init".environment.VPN_SOURCE_CONFIG == $profile) and
    (.services."ddns-watcher".environment.VPN_SOURCE_CONFIG == $profile) and
    (.services."ddns-init".environment.VPN_SOURCE_SHA256 == $profile_hash) and
    (.services."ddns-watcher".environment.VPN_SOURCE_SHA256 == $profile_hash) and
    (.services.gluetun.environment.OPENVPN_CUSTOM_CONFIG == "/state/runtime/vpn.conf") and

    (.services."ddns-init".environment.DDNS_POLL_SECONDS == "60") and
    (.services."ddns-init".environment.DDNS_INIT_RETRY_SECONDS == "5") and
    (.services."ddns-init".environment.DDNS_INIT_TIMEOUT_SECONDS == "120") and
    (.services."ddns-init".environment.GLUETUN_HEALTH_TIMEOUT_SECONDS == "120") and
    (.services."ddns-watcher".environment.DDNS_POLL_SECONDS == "60") and
    (.services."ddns-watcher".environment.DDNS_INIT_RETRY_SECONDS == "5") and
    (.services."ddns-watcher".environment.DDNS_INIT_TIMEOUT_SECONDS == "120") and
    (.services."ddns-watcher".environment.GLUETUN_HEALTH_TIMEOUT_SECONDS == "120") and
    (.services."ddns-init".environment.DDNS_OVERRIDE_IPS == "") and
    (.services."ddns-watcher".environment.DDNS_OVERRIDE_IPS == "") and
    (.services."ddns-init".environment.PROXY_BIND_ADDRESS == "127.0.0.1") and
    (.services."ddns-watcher".environment.PROXY_BIND_ADDRESS == "127.0.0.1") and
    (.services."ddns-init".environment.OPENVPN_USER_CONFIGURED == "1") and
    (.services."ddns-init".environment.OPENVPN_PASSWORD_CONFIGURED == "1") and
    (.services."ddns-init".environment.HTTPPROXY_ENABLED == "on") and
    (.services."ddns-init".environment.HTTPPROXY_USER_CONFIGURED == "1") and
    (.services."ddns-init".environment.HTTPPROXY_PASSWORD_CONFIGURED == "1") and
    (.services."ddns-init".environment.SOCKS5_USER_CONFIGURED == "0") and
    (.services."ddns-init".environment.SOCKS5_PASSWORD_CONFIGURED == "0") and
    (.services."ddns-init".environment.SHADOWSOCKS_ENABLED == "on") and
    (.services."ddns-init".environment.SHADOWSOCKS_PASSWORD_CONFIGURED == "1") and
    (.services.gluetun.environment.OPENVPN_USER_SECRETFILE == "/run/ddns-private/openvpn-user") and
    (.services.gluetun.environment.OPENVPN_PASSWORD_SECRETFILE == "/run/ddns-private/openvpn-password") and
    (.services.gluetun.environment.HTTPPROXY == "on") and
    (.services.gluetun.environment.HTTPPROXY_USER_SECRETFILE == "/run/ddns-private/httpproxy-user") and
    (.services.gluetun.environment.HTTPPROXY_PASSWORD_SECRETFILE == "/run/ddns-private/httpproxy-password") and
    (.services.gluetun.environment.HTTPPROXY_STEALTH == "off") and
    (.services.gluetun.environment.SHADOWSOCKS == "on") and
    (.services.gluetun.environment.SHADOWSOCKS_PASSWORD_SECRETFILE == "/run/ddns-private/shadowsocks-password") and
    (.services.gluetun.environment.SHADOWSOCKS_CIPHER == "chacha20-ietf-poly1305") and
    ((.services.vproxy.environment // {}) == {}) and
    (.services."ddns-init".environment.GLUETUN_CONTROL_AUTH_CONFIG_FILEPATH ==
      "/run/ddns-private/control-auth.toml") and
    (.services."ddns-init".environment.GLUETUN_CONTROL_DEFAULT_ROLE_FILE ==
      "/run/ddns-private/control-default-role.json") and
    (.services."ddns-init".environment.OPENVPN_USER_SECRETFILE ==
      "/run/ddns-private/openvpn-user") and
    (.services."ddns-init".environment.OPENVPN_PASSWORD_SECRETFILE ==
      "/run/ddns-private/openvpn-password") and
    (.services."ddns-init".environment.HTTPPROXY_USER_SECRETFILE ==
      "/run/ddns-private/httpproxy-user") and
    (.services."ddns-init".environment.HTTPPROXY_PASSWORD_SECRETFILE ==
      "/run/ddns-private/httpproxy-password") and
    (.services."ddns-init".environment.SHADOWSOCKS_PASSWORD_SECRETFILE ==
      "/run/ddns-private/shadowsocks-password") and

    ((.services.gluetun.ports | length) == 4) and
    (.services.gluetun.ports == [
      {"mode":"ingress","host_ip":"127.0.0.1","target":8888,"published":$http,"protocol":"tcp"},
      {"mode":"ingress","host_ip":"127.0.0.1","target":1080,"published":$socks,"protocol":"tcp"},
      {"mode":"ingress","host_ip":"127.0.0.1","target":8388,"published":$ss_tcp,"protocol":"tcp"},
      {"mode":"ingress","host_ip":"127.0.0.1","target":8388,"published":$ss_udp,"protocol":"udp"}
    ]) and
    (all(.services | to_entries[];
      (.key == "gluetun") or (((.value.ports // []) | length) == 0))) and
    has_port(8888; $http; "tcp") and
    has_port(1080; $socks; "tcp") and
    has_port(8388; $ss_tcp; "tcp") and
    has_port(8388; $ss_udp; "udp") and
    (all(.services.gluetun.ports[]; .target != 8000 and .target != 9999)) and

    (.services.gluetun.environment.HTTP_CONTROL_SERVER_ADDRESS == ":8000") and
    (.services.gluetun.environment.FIREWALL_INPUT_PORTS == "8888,1080,8388,8000,9999") and
    (.services.gluetun.environment.HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH ==
      "/run/ddns-private/control-auth.toml") and
    (.services.gluetun.entrypoint == ["/bin/sh", "-ec"]) and
    (any(.services.gluetun.command[]; contains("HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE"))) and
    (any(.services.gluetun.command[]; contains("control-default-role.json"))) and
    (any(.services.gluetun.command[]; contains("/etc/resolv.conf"))) and
    (any(.services.gluetun.command[]; contains("nameserver 127.0.0.1"))) and
    (any(.services.gluetun.command[]; contains("1000:1000"))) and
    (any(.services.gluetun.command[]; contains("test ! -L"))) and
    (any(.services.gluetun.command[]; contains("stat -c"))) and
    (any(.services.gluetun.command[]; contains("default_key"))) and
    (any(.services.gluetun.command[]; contains("expected_auth"))) and
    (any(.services.gluetun.command[];
      contains("test \"$${actual_auth}\" = \"$${expected_auth}\""))) and
    (any(.services.gluetun.command[]; contains("exec /gluetun-entrypoint"))) and
    (.services."ddns-init".environment.GLUETUN_CONTROL_API_KEY_FILE ==
      "/run/ddns-private/control-api-key") and
    (.services."ddns-watcher".environment.GLUETUN_CONTROL_API_KEY_FILE ==
      "/run/ddns-private/control-api-key") and
    (.services."ddns-init".volumes == [
      ro_bind($helper_source; "/usr/local/bin/ddns-openvpn.sh"),
      ro_bind($profile_source; "/opt/ddns-profile/client.ovpn"),
      ro_bind(($private_source + "/control-api-key"); "/run/ddns-private/control-api-key"),
      ro_bind(($private_source + "/control-auth.toml"); "/run/ddns-private/control-auth.toml"),
      ro_bind(($private_source + "/control-default-role.json"); "/run/ddns-private/control-default-role.json"),
      rw_state
    ]) and
    (.services."ddns-watcher".volumes == [
      ro_bind($helper_source; "/usr/local/bin/ddns-openvpn.sh"),
      ro_bind($profile_source; "/opt/ddns-profile/client.ovpn"),
      ro_bind(($private_source + "/control-api-key"); "/run/ddns-private/control-api-key"),
      rw_state
    ]) and
    (.services.gluetun.volumes == [
      ro_bind(($private_source + "/control-api-key"); "/run/ddns-private/control-api-key"),
      ro_bind(($private_source + "/control-auth.toml"); "/run/ddns-private/control-auth.toml"),
      ro_bind(($private_source + "/control-default-role.json"); "/run/ddns-private/control-default-role.json"),
      ro_bind(($private_source + "/openvpn-user"); "/run/ddns-private/openvpn-user"),
      ro_bind(($private_source + "/openvpn-password"); "/run/ddns-private/openvpn-password"),
      ro_bind(($private_source + "/httpproxy-user"); "/run/ddns-private/httpproxy-user"),
      ro_bind(($private_source + "/httpproxy-password"); "/run/ddns-private/httpproxy-password"),
      ro_bind(($private_source + "/shadowsocks-password"); "/run/ddns-private/shadowsocks-password"),
      rw_bind($runtime_source; "/etc/resolv.conf"),
      ro_state
    ]) and
    readonly_bind("ddns-init"; $helper_source; "/usr/local/bin/ddns-openvpn.sh") and
    readonly_bind("ddns-init"; $profile_source; "/opt/ddns-profile/client.ovpn") and
    readonly_bind("ddns-init"; ($private_source + "/control-api-key");
      "/run/ddns-private/control-api-key") and
    readonly_bind("ddns-init"; ($private_source + "/control-auth.toml");
      "/run/ddns-private/control-auth.toml") and
    readonly_bind("ddns-init"; ($private_source + "/control-default-role.json");
      "/run/ddns-private/control-default-role.json") and
    named_volume("ddns-init"; "vpn-state"; "/state"; false) and
    ((.services."ddns-init".volumes | length) == 6) and

    readonly_bind("ddns-watcher"; $helper_source; "/usr/local/bin/ddns-openvpn.sh") and
    readonly_bind("ddns-watcher"; $profile_source; "/opt/ddns-profile/client.ovpn") and
    readonly_bind("ddns-watcher"; ($private_source + "/control-api-key");
      "/run/ddns-private/control-api-key") and
    named_volume("ddns-watcher"; "vpn-state"; "/state"; false) and
    ((.services."ddns-watcher".volumes | length) == 4) and

    readonly_bind("gluetun"; ($private_source + "/control-api-key");
      "/run/ddns-private/control-api-key") and
    readonly_bind("gluetun"; ($private_source + "/control-auth.toml");
      "/run/ddns-private/control-auth.toml") and
    readonly_bind("gluetun"; ($private_source + "/control-default-role.json");
      "/run/ddns-private/control-default-role.json") and
    readonly_bind("gluetun"; ($private_source + "/openvpn-user");
      "/run/ddns-private/openvpn-user") and
    readonly_bind("gluetun"; ($private_source + "/openvpn-password");
      "/run/ddns-private/openvpn-password") and
    readonly_bind("gluetun"; ($private_source + "/httpproxy-user");
      "/run/ddns-private/httpproxy-user") and
    readonly_bind("gluetun"; ($private_source + "/httpproxy-password");
      "/run/ddns-private/httpproxy-password") and
    readonly_bind("gluetun"; ($private_source + "/shadowsocks-password");
      "/run/ddns-private/shadowsocks-password") and
    named_volume("gluetun"; "vpn-state"; "/state"; true) and
    ((.services.gluetun.volumes | length) == 10) and
    (((.services.vproxy.volumes // []) | length) == 0) and
    (all(.services[];
      all((.volumes // [])[]; .source != "/var/run/docker.sock")))
  ' "$model" >/dev/null ||
  die 'Portainer env or rendered Compose contract does not match the reviewed region'

# The key-backed role is deliberately status-only. Endpoint/settings mutation
# would expand authority beyond the reviewed stop/start reload sequence.
grep -Fq 'X-API-Key:' "$helper" ||
  die 'helper does not authenticate Gluetun control requests with X-API-Key'
grep -Fq 'gluetun_control_put /v1/vpn/status' "$helper" ||
  die 'helper does not use the reviewed VPN status endpoint'
if grep -Fq '/v1/vpn/settings' "$helper"; then
  die 'helper still requires VPN settings authority; status-only role assumption failed'
fi

printf 'Portainer env contract valid for %s with Stack Name %s (secrets not printed).\n' \
  "$region" "$stack_name"
