services:
  phpmyadmin: 
    image: lscr.io/linuxserver/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    network_mode: bridge
    ports:
    # web ui
      - 53306:80
    environment:
      # Set to `1` to allow you to connect to any server. Setting to `0` will only allow you to connect to specified hosts (See Application Setup)
      - PMA_ARBITRARY=1
      # Set the URL you will use to access the web frontend
      - PMA_ABSOLUTE_URI=http://phpmyadmin.dfder.tw
      # for permission issue
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
    volumes:
      - /mnt/appdata/phpmyadmin:/config
    networks:
      - appnetwork
networks:
  appnetwork:
    name: mynetwork
    external: true
      
      