# author: df
# version: 3.0
# date: 2024.8.19
# description: linux-do-bot for keep alive in linux.do


# This is the 4th generation of linux-do-bot. damn it.
# doc: https://linux.do/t/topic/281588
services:
  linuxdo-a:
    image: ruk1ng/auto-linuxdo:latest
    container_name: auto-linuxdo-a
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /mnt/appdata/linux.do-Bot/logs/a:/app/logs
      - /mnt/appdata/linux.do-Bot/config-a.yaml:/app/config.yaml
      - /mnt/appdata/linux.do-Bot/cookies/a:/app/cookies

  linuxdo-b:
    image: ruk1ng/auto-linuxdo:latest
    container_name: auto-linuxdo-b
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /mnt/appdata/linux.do-Bot/logs/b:/app/logs
      - /mnt/appdata/linux.do-Bot/config-b.yaml:/app/config.yaml
      - /mnt/appdata/linux.do-Bot/cookies/b:/app/cookies






