# author: df
# version: 3.0
# date: 2024.8.19
# description: linux-do-bot for keep alive in linux.do


# This is the 4th generation of linux-do-bot. damn it.
# doc: https://linux.do/t/topic/281588
services:
  linuxdo-a:
    image: ruk1ng/auto-linuxdo:latest
    container_name: auto-linuxdo-a
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /mnt/appdata/linux.do-Bot/logs/a:/app/logs
      - /mnt/appdata/linux.do-Bot/config-a.yaml:/app/config.yaml
      - /mnt/appdata/linux.do-Bot/cookies/a:/app/cookies
    network_mode: "service:gluetun-tw"

  linuxdo-b:
    image: ruk1ng/auto-linuxdo:latest
    container_name: auto-linuxdo-b
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /mnt/appdata/linux.do-Bot/logs/b:/app/logs
      - /mnt/appdata/linux.do-Bot/config-b.yaml:/app/config.yaml
      - /mnt/appdata/linux.do-Bot/cookies/b:/app/cookies
    network_mode: "service:gluetun-jp"

  gluetun-tw:
    image: qmcgaw/gluetun
    # container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    # ports:
      # - 28888:8888/tcp # HTTP proxy
      # - 28388:8388/tcp # Shadowsocks
      # - 28388:8388/udp # Shadowsocks
    volumes:
        # /gluetun/wireguard/wg0.conf  is the wireguard configuration file
      - /mnt/appdata/gluetun:/gluetun
      # - /mnt/appdata/gluetun/wireguard/tw.conf:/gluetun/wg0.conf
      
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard 
      # OpenVPN:
      # - OPENVPN_USER=
      # - OPENVPN_PASSWORD=
      # Wireguard:
      
      # - WIREGUARD_PUBLIC_KEY=bI5kgFePO/UfyU/Apd7AYtd168PZ8MiaV97csUYGvlk=
      - WIREGUARD_PRIVATE_KEY= ${SURFSHARK_WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=10.14.0.2/16
      - SERVER_COUNTRIES=Taiwan
      # - WIREGUARD_ENDPOINT_PORT=
      # - WIREGUARD_ENDPOINT_IP=1.2.3.4 
      # Timezone for accurate log times
      - TZ=Asia/Taipei
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD= 24h

  gluetun-jp:
    image: qmcgaw/gluetun
    # container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    # ports:
      # - 28888:8888/tcp # HTTP proxy
      # - 28388:8388/tcp # Shadowsocks
      # - 28388:8388/udp # Shadowsocks
    volumes:
        # /gluetun/wireguard/wg0.conf  is the wireguard configuration file
      - /mnt/appdata/gluetun:/gluetun
      # - /mnt/appdata/gluetun/wireguard/jp.conf:/gluetun/wg0.conf
      
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard 
      # OpenVPN:
      # - OPENVPN_USER=
      # - OPENVPN_PASSWORD=
      # Wireguard:
      
      # - WIREGUARD_PUBLIC_KEY=bI5kgFePO/UfyU/Apd7AYtd168PZ8MiaV97csUYGvlk=
      - WIREGUARD_PRIVATE_KEY= ${SURFSHARK_WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=10.14.0.2/16
      - SERVER_COUNTRIES=Japan
      # - WIREGUARD_ENDPOINT_PORT=
      # - WIREGUARD_ENDPOINT_IP=1.2.3.4 
      # Timezone for accurate log times
      - TZ=Asia/Taipei
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD= 24h



