# author: df
# version: 1.0
# date: 2024.8.19
# description: linux-do-bot for keep alive in linux.do
# doc: https://github.com/lee0692/linux-do-bot

version: '3'
services:
  linux-do-bot:
    image: lee0692/linux-do-bot
    container_name: linux-do-bot-container
    environment:
      - LINUXDO_USERNAME=${DF_ID}
      - LINUXDO_PASSWORD=${DF_PASSWORD}
      - LIKE_PROBABILITY=0.1
      - REPLY_PROBABILITY=0
      - COLLECT_PROBABILITY=0.1
      - MAX_TOPICS=32
      - USE_WXPUSHER=false
      - APP_TOKEN=your_app_token
      - TOPIC_ID=your_topic_id
    restart: unless-stopped
    networks:
      - appnetwork
networks:
  appnetwork:
    name: mynetwork
    external: true