version: "3.9"

services:
  unifi-cam-proxy:
    restart: unless-stopped

    # the original repo
    # image: keshavdv/unifi-cam-proxy:dev
    # yolo
    build: https://github.com/JasonGehring/unifi-cam-proxy.git
    volumes:
      - /mnt/appdata/unifi-cam-proxy/client.pem:/client.pem
    command: unifi-cam-proxy --host 192.168.10.1 --cert /client.pem --token oYOGWN7wIkq7N35Na7Sqqw6oVXIoC1hk --model "UVC G4 PTZ" --ip="192.168.11.109" tapo --username="tapocam" --password="zxcv6319" --rtsp rtsp://tapocam:zxcv6319@192.168.11.109:554/stream1