# doc: https://github.com/SuperNG6/Docker-qBittorrent-Enhanced-Edition

services:
  bt-gluetun:
    image: qmcgaw/gluetun
    container_name: bt-gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # qBittorrent WebUI
      - 58080:58080/tcp
      # qBittorrent BT PORT
      - 51001:51001/tcp
      - 51001:51001/udp
    volumes:
      - /mnt/appdata/qbittorrent-enhanced/gluetun:/gluetun
    environment:
      # 基本 VPN 設定 (必填)
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
      # 系統設定
      - TZ=${TZ}
      - UMASK=000
      # 伺服器選擇 (可選)
      # - SERVER_COUNTRIES="Romania"
      # - SERVER_REGIONS="București"
      # - SERVER_CITIES="Bucharest"
      # - SERVER_HOSTNAMES="ro2-auto-udp.ptoserver.com"
    env_file: .env

  qbittorrent-enhanced:
    image: superng6/qbittorrentee
    container_name: qbittorrent-enhanced
    restart: unless-stopped
    network_mode: "container:bt-gluetun"
    depends_on:
      - bt-gluetun
    volumes:
      - /mnt/mydata/BT/qbittorrentDownloads/data:/data
      - /mnt/appdata/qbittorrent-enhanced/qbittorrent-enhanced-config:/config
    environment:
      # 系統設定
      - TZ=${TZ}
      - UMASK=000
      - PGID=3000
      - PUID=3000
      # qBittorrent 設定
      - WEBUIPORT=58080
      - ENABLE_ata_PERM_FIX=false

    env_file: .env
