name: hometheaterstack
services:
  jellyseerr: 
    image: fallenbagel/jellyseerr:latest
    restart: unless-stopped
    container_name: jellyseerr
    ports:
    # WebUI  port
      - 55055:5055
    volumes:
      # appdata
      - /mnt/appdata/jellyseerr:/app/config/
    environment:
      # Log verbosity.
      - LOG_LEVEL=info
      # Emby users need to fill 'emby' to enable emby support! Enabling emby support will cause problems with Plex and make Jellyfin unavailable.
      - JELLYFIN_TYPE=jellyfin

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    container_name: jellyfin
    ports:
      # Http webUI.
      - 8096:8096
      # optional - Https webUI (you need to set up your own certificate).
      - 8920:8920
      # Optional - Allows clients to discover Jellyfin on the local network
      - 7359:7359
      # Optional - Service discovery used by DNLA and clients.
      - 1900:1900
  
    volumes:
      # Jellyfin data storage location. *This can grow very large, 50gb+ is likely for a large collection.*
      - /mnt/appdata/jellyfin:/config
      # Media goes here. Add as many as needed e.g. `/data/movies`, `/data/tv`, etc.
      - /mnt/mydata/Public/movies:/data/movies
      - /mnt/mydata/Public/ACGN:/data/ACGN
      - /mnt/mydata/Public/Music:/data/music
      - /mnt/mydata/Public/TVs:/data/tvs
      # pass downloader ACGN-online folder to auto import to library
      - /mnt/mydata/diskMigration/BrokenHDD_BeCareful/qbittorrentDownloads/data/FinishedBox/ACGN-online:/data/ACGN-online
      # pass autobangumi folder
      - /mnt/mydata/diskMigration/BrokenHDD_BeCareful/qbittorrentDownloads/data/AutoBangumi:/data/AutoBangumi
      
    environment:
      # https://github.com/linuxserver/docker-jellyfin#nvidia or https://jellyfin.org/docs/general/administration/hardware-acceleration/nvidia/
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      # Set the autodiscovery response domain or IP address.
      - JELLYFIN_PublishedServerUrl=theater.dfder.tw
    devices:
      - "/dev/nvidia0:/dev/nvidia0"                 # Nvidia CUDA
      - "/dev/nvidiactl:/dev/nvidiactl"
      # - "/dev/nvidia-modeset:/dev/nvidia-modeset"     ???????Quantem state?   
      # - "/dev/nvidia-nvswitchctl:/dev/nvidia-nvswitchctl" This one is not in my system
      - "/dev/nvidia-uvm:/dev/nvidia-uvm"
      - "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: [gpu, compute, video]  
    # for nvidia gpu pass. 反正flag我就給爆。垃圾nv
    # runtime: nvidia   # 這個不能給 不然會爆 阿為什麼窩不知道
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
            

  jackett:
    restart: unless-stopped
    container_name: jackett
    image: lscr.io/linuxserver/jackett
    ports:
      # webui 
      - 9117:9117
    volumes:
      # Path to torrent blackhole.
      - /mnt/mydata/theaterStack/jackeetTorrents:/downloads
      # Where Jackett should store its config file.
      - /mnt/appdata/jackett:/config
    environment:
      #Allow Jackett to update inside of the container (currently recommended by Jackett and enabled by default)
      - AUTO_UPDATE=true
      #Optionally specify additional arguments to be passed
      - RUN_OPTS=

  jproxy:
    image: luckypuppy514/jproxy:latest
    container_name: jproxy
    restart: unless-stopped
    ports:
      # web ui
      - 8117:8117
    environment:
      - TZ=Asia/Taipei
      - JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      # appdata
      - /mnt/appdata/jproxy:/app/database

  # This is for metatube scratching metadata. Ref: https://metatube-community.github.io/wiki/server-deployment/
  # I use sqlite for easier deployment
  metatube-server:
    container_name: metatube
    restart: unless-stopped
    image: metatube/metatube-server:latest
    ports:
      - 48080:8080
    volumes:
      - /mnt/appdata/metatube-server/config:/config
    command: -dsn /config/metatube.db
  
  # Autobangumi for 自動追番。 replace my own rough download chain. REF: https://www.autobangumi.org/home/

  AutoBangumi:
    image: "ghcr.io/estrellaxd/auto_bangumi:latest"
    container_name: AutoBangumi
    restart: unless-stopped
    volumes:
      - /mnt/appdata/AutoBangumi/config:/app/config
      # The data folder seems not used too much storage, so I just put it in the appdata  folder
      - /mnt/appdata/AutoBangumi/data:/app/data
    ports:
      - "7892:7892"
    dns:
    # the default use aliyun. I replace it with my own dns
    # my own dns seems not work. use cloudflare
      - 1.1.1.1
    environment:
      - TZ=Asia/Taipei
      # the logs show the PUID and PGID is not set. use my default env
      # - PGID=$(id -g)
      # - PUID=$(id -u)
      - UMASK=022


