# reference https://github.com/peakxl/twitch-drop-claimer
version: '3.5'
services:
  twitch-drop-claimer:
    image: peakxy/twitch-watcher:latest
    restart: unless-stopped
    environment:
      - auth_token=${DF_AUTHTOKEN}  # my own token
      - category=warthunder
      - watchAlwaysTopStreamer=true
      - claimDrops=true
      - channelsWithPriority=WarThunder_eSports,rainbow6,muse_tw, rainbow6
      #- noChannelFoundWait=5
      #- userAgent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
      #- minWatching=15
      #- maxWatching=30
      #- streamerListRefresh=2
      #- streamerListRefreshUnit=hour
      #- browserScreenshot=false
      #- proxy=ip:port
      #- proxyAuth=username:password
    volumes:
     - /mnt/appdata:/usr/src/app/screenshots
