version: "3.3"
services:
  portainer_agent:
    image: portainer/agent
    restart: always
    container_name: portainer_agent
    ports:
      - 29001:9001
    
    volumes:
      # To enable host management. Ref: https://docs.portainer.io/user/docker/host/setup#enable-host-management-features
      - /:/host
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    
