services:
  adg: 
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    ports:
    # dns tcp udp
      - 53:53
      - 53:53/udp
    # dns over tls
      - 853:853
    # 853:853 udp
      - 853:853/udp
    # WebUI:
      - 3000:3000
    volumes:
    # working dir
      - /mnt/appdata/adguard_home/workingdir:/opt/adguardhome/work
    # config dir
      - /mnt/appdata/adguard_home/config:/opt/adguardhome/conf
    networks:
      - appnetwork
networks:
  appnetwork:
    name: mynetwork
    external: true