services:
  adg: 
    image: xhofe/alist:latest
    container_name: alist
    ports:
    # Web UI port
      - 5244:5244
    volumes:
      # download data
      - /mnt/mydata/Alist_dir:/mnt/data
      # appdata 
      - /mnt/appdata/alist:/opt/alist/data
# ---
  