services:
  alist: 
    image: xhofe/alist:latest
    restart: unless-stopped
    container_name: alist
    network_mode: bridge
      - networkName
    ports:
    # container ports
      - 5244:5244
    volumes:
    # download
      - /mnt/mydata/Alist_dir:/mnt/data
    # appdata config
      - /mnt/appdata/alist:/opt/alist/data
