services:
  alist: 
    image: xhofe/alist:latest
    restart: unless-stopped
    container_name: alist
    ports:
    # container ports
      - 5244:5244
    # sftp access  
      - 5222:5222
    volumes:
    # download
      - /mnt/mydata/Alist_dir:/mnt/data
    # appdata config
      - /mnt/appdata/alist:/opt/alist/data

      

