services:
  alist: 
    image: xhofe/alist:latest
    restart: unless-stopped
    container_name: alist
      - networkName
    ports:
    # container ports
      - 5244:5244
    volumes:
    # download
      - /mnt/mydata/Alist_dir:/mnt/data
    # appdata config
      - /mnt/appdata/alist:/opt/alist/data
    networks:
      - app_network
  networks:
  app_network:
    name: mynetwork
    external: true
      

