
version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - /home/df/uptime-kuma-data:/app/data 
    ports:
      - 53001:3001
