name=Dracula
description=Current purple/pink Dracula Homepage theme with its original assets.
theme=dark
color=gray
headerStyle=underlined
statusStyle=dot
iconStyle=theme
cardBlur=omit
fullWidth=true
maxGroupColumns=6
maxBookmarkGroupColumns=6
background=image
backgroundImage=/images/Dracula.png
backgroundBlur=sm
backgroundSaturate=70
backgroundBrightness=45
backgroundOpacity=60
css=dracula
