# Author: df
# Version: 1.0
# Date: 2024.10.18
# Description: immich aio version
# Doc: https://github.com/imagegenius/docker-immich

---
services:
  immich-aio:
    image: ghcr.io/imagegenius/immich:cuda
    container_name: immich-aio
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
      - DB_HOSTNAME=postgres14
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - MACHINE_LEARNING_HOST=0.0.0.0 #optional
      - MACHINE_LEARNING_PORT=3003 #optional
      - MACHINE_LEARNING_WORKERS= #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
    volumes:
      - /mnt/appdata/immich-aio/config:/config
      # this is the upload location
      - /mnt/appdata/immich-aio/photos:/photos
      # this is for external library
      - /mnt/fastpool/HomePhotos:/libraries:ro #optional
    ports:
      - 38080:8080
    restart: unless-stopped

# This container requires an external application to be run separately.
# By default, ports for the databases are opened, be careful when deploying it
# Redis:
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
# PostgreSQL 14:
  postgres14:
    image: tensorchord/pgvecto-rs:pg14-v0.3.0
    ports:
      - 5432:5432
    container_name: postgres14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - /mnt/appdata/immich-aio/postgres:/var/lib/postgresql/data

